import { useState, type FormEvent } from "react";
import { Badge, Button, Card, ErrorState, Field, Input, Select, useAsync } from "@eops/ui";
import { FieldNav } from "../components/FieldNav";
import { fieldTeamsService } from "../services/fieldTeamsService";
import styles from "../styles/fieldTeams.module.css";

export function ChecksPage() {
  const checks = useAsync(fieldTeamsService.checks, []); const members = useAsync(fieldTeamsService.members, []); const references = useAsync(fieldTeamsService.references, []);
  const [form, setForm] = useState({ memberId: "", electoralZoneId: "", pollingPlaceId: "", type: "CHECK_IN" as "CHECK_IN" | "CHECK_OUT", occurredAt: new Date().toISOString().slice(0, 16), notes: "" }); const [error, setError] = useState<Error>();
  const places = references.data?.places.filter((item) => !form.electoralZoneId || item.electoralZoneId === form.electoralZoneId) ?? [];
  async function submit(event: FormEvent) { event.preventDefault(); try { await fieldTeamsService.createCheck({ ...form, electoralZoneId: form.electoralZoneId || undefined, pollingPlaceId: form.pollingPlaceId || undefined, occurredAt: new Date(form.occurredAt).toISOString(), notes: form.notes || undefined }); checks.reload(); members.reload(); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Falha ao registrar presença.")); } }
  return <section className={styles.page}><FieldNav /><header className={styles.header}><div><span>PRESENÇA</span><h1>Check-in e check-out</h1><p>Registro operacional de presença por pessoa e local, sem coleta de GPS.</p></div></header>{error && <ErrorState error={error} />}<div className={styles.columns}><Card><h2>Novo registro</h2><form className={styles.form} onSubmit={submit}><Field label="Membro"><Select required value={form.memberId} onChange={(event) => setForm((value) => ({ ...value, memberId: event.target.value }))}><option value="">Selecione</option>{members.data?.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.team?.name}</option>)}</Select></Field><Field label="Tipo"><Select value={form.type} onChange={(event) => setForm((value) => ({ ...value, type: event.target.value as "CHECK_IN" | "CHECK_OUT" }))}><option value="CHECK_IN">Check-in</option><option value="CHECK_OUT">Check-out</option></Select></Field><Field label="Zona"><Select value={form.electoralZoneId} onChange={(event) => setForm((value) => ({ ...value, electoralZoneId: event.target.value, pollingPlaceId: "" }))}><option value="">Sem zona</option>{references.data?.zones.map((item) => <option key={item.id} value={item.id}>Zona {item.number} · {item.name}</option>)}</Select></Field><Field label="Local"><Select value={form.pollingPlaceId} onChange={(event) => setForm((value) => ({ ...value, pollingPlaceId: event.target.value }))}><option value="">Sem local</option>{places.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Horário"><Input required type="datetime-local" value={form.occurredAt} onChange={(event) => setForm((value) => ({ ...value, occurredAt: event.target.value }))} /></Field><Field label="Observação"><Input value={form.notes} onChange={(event) => setForm((value) => ({ ...value, notes: event.target.value }))} /></Field><Button type="submit">Registrar</Button></form></Card><Card><h2>Histórico recente</h2><div className={styles.list}>{checks.data?.map((item) => <article key={item.id}><div><strong>{item.member.name}</strong><span>{item.pollingPlace?.name ?? (item.electoralZone ? `Zona ${item.electoralZone.number}` : "Local não informado")}</span><small>{new Date(item.occurredAt).toLocaleString("pt-BR")}</small></div><Badge tone={item.type === "CHECK_IN" ? "success" : "neutral"}>{item.type.replace("_", "-")}</Badge></article>)}</div></Card></div></section>;
}
