import { useState, type FormEvent } from "react";
import { Badge, Button, Card, EmptyState, ErrorState, Field, Input, Loading, Select, useAsync } from "@eops/ui";
import { Link } from "react-router-dom";
import { FieldNav } from "../components/FieldNav";
import { fieldTeamsService } from "../services/fieldTeamsService";
import styles from "../styles/fieldTeams.module.css";

export function TeamsPage() {
  const teams = useAsync(fieldTeamsService.teams, []); const references = useAsync(fieldTeamsService.references, []);
  const [form, setForm] = useState({ name: "", code: "", electionId: "", responsibleName: "", notes: "" }); const [error, setError] = useState<Error>();
  async function submit(event: FormEvent) { event.preventDefault(); try { await fieldTeamsService.createTeam({ ...form, status: "ACTIVE" }); setForm({ name: "", code: "", electionId: "", responsibleName: "", notes: "" }); teams.reload(); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Falha ao criar equipe.")); } }
  return <section className={styles.page}><FieldNav /><header className={styles.header}><div><span>EQUIPES</span><h1>Equipes operacionais</h1><p>Cadastro, contatos e estado das equipes por pleito.</p></div></header>{error && <ErrorState error={error} />}<div className={styles.columns}><Card><h2>Nova equipe</h2><form className={styles.form} onSubmit={submit}><Field label="Nome"><Input required value={form.name} onChange={(event) => setForm((value) => ({ ...value, name: event.target.value }))} /></Field><Field label="Código"><Input required value={form.code} onChange={(event) => setForm((value) => ({ ...value, code: event.target.value }))} /></Field><Field label="Pleito"><Select required value={form.electionId} onChange={(event) => setForm((value) => ({ ...value, electionId: event.target.value }))}><option value="">Selecione</option>{references.data?.elections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Responsável"><Input required value={form.responsibleName} onChange={(event) => setForm((value) => ({ ...value, responsibleName: event.target.value }))} /></Field><Field label="Observações"><Input value={form.notes} onChange={(event) => setForm((value) => ({ ...value, notes: event.target.value }))} /></Field><Button type="submit">Criar equipe</Button></form></Card><Card><h2>Equipes</h2>{teams.loading && <Loading />}{teams.error && <ErrorState error={teams.error} />}{teams.data?.length === 0 && <EmptyState title="Nenhuma equipe" description="Cadastre a primeira equipe de campo." />}<div className={styles.list}>{teams.data?.map((team) => <Link key={team.id} to={`/field-teams/teams/${team.id}`}><div><strong>{team.code} · {team.name}</strong><span>{team.election.name} · Responsável: {team.responsibleName}</span></div><div><Badge tone={team.status === "ACTIVE" ? "success" : "neutral"}>{team.status}</Badge><span>{team.members.length} membros</span></div></Link>)}</div></Card></div></section>;
}
