import { useState, type FormEvent } from "react";
import { Badge, Button, Card, ErrorState, Field, Input, Loading, Select, useAsync } from "@eops/ui";
import { userService } from "../services/authService";
import { useAuth } from "../AuthContext";
import styles from "../styles/access.module.css";

export function UserListPage() {
  const users = useAsync(userService.list, []); const roles = useAsync(userService.roles, []); const { hasPermission } = useAuth(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [roleId, setRoleId] = useState(""); const [error, setError] = useState<unknown>();
  async function submit(event: FormEvent) { event.preventDefault(); setError(undefined); try { await userService.create({ name, email, password, roleIds: [roleId] }); setName(""); setEmail(""); setPassword(""); users.reload(); } catch (cause) { setError(cause); } }
  return <section className={styles.page}><header><span>SISTEMA</span><h1>Usuários e Acessos</h1><p>Perfis agrupam permissões validadas também pela API.</p></header>{users.loading && <Loading />}{users.error && <ErrorState error={users.error} onRetry={users.reload} />}{error !== undefined && <ErrorState error={error} />}<div className={styles.grid}>{hasPermission("users.manage") && <Card><h2>Novo usuário</h2><form onSubmit={(event) => void submit(event)}><Field label="Nome"><Input required value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="E-mail"><Input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></Field><Field label="Senha inicial"><Input required type="password" minLength={10} value={password} onChange={(event) => setPassword(event.target.value)} /></Field><Field label="Perfil"><Select required value={roleId} onChange={(event) => setRoleId(event.target.value)}><option value="">Selecione</option>{roles.data?.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</Select></Field><Button type="submit">Criar usuário</Button></form></Card>}<Card><h2>Usuários</h2><ul className={styles.users}>{users.data?.map((user) => <li key={user.id}><div><strong>{user.name}</strong><span>{user.email}</span></div><div>{user.roles.map(({ role }) => <Badge key={role.id}>{role.name}</Badge>)}</div><Badge tone={user.status === "ACTIVE" ? "success" : "danger"}>{user.status}</Badge></li>)}</ul></Card></div></section>;
}
