import { useState, type FormEvent } from "react";
import { Breadcrumb, Button, Card, EmptyState, ErrorState, Field, Input, LinkButton, Loading, Select, useAsync } from "@eops/ui";
import { ASSET_CONDITIONS, ASSET_CONDITION_LABELS, type AssetCondition } from "@eops/shared/inventory";
import { formatDateTime } from "@eops/shared/format";
import { Link, useParams } from "react-router-dom";
import { AssetConditionBadge, AssetStatusBadge } from "../components/AssetBadge";
import { inventoryService } from "../services/inventoryService";
import styles from "../styles/inventory.module.css";

export function AssetDetailPage() {
  const { id = "" } = useParams();
  const asset = useAsync(() => inventoryService.get(id), [id]);
  const [error, setError] = useState<Error>();
  const [checkout, setCheckout] = useState({ responsibleName: "", purpose: "", origin: "", destination: "", expectedReturnAt: "", conditionOut: "GOOD" as AssetCondition, notes: "" });
  const [checkin, setCheckin] = useState({ conditionIn: "GOOD" as AssetCondition, returnedTo: "", receivedByName: "", problemDetected: false, notes: "" });
  async function submitCheckout(event: FormEvent) {
    event.preventDefault(); setError(undefined);
    try { await inventoryService.checkOut(id, { ...checkout, expectedReturnAt: checkout.expectedReturnAt ? new Date(checkout.expectedReturnAt).toISOString() : undefined }); asset.reload(); }
    catch (reason) { setError(reason instanceof Error ? reason : new Error("Não foi possível registrar a retirada.")); }
  }
  async function submitCheckin(event: FormEvent) {
    event.preventDefault(); setError(undefined);
    try { await inventoryService.checkIn(id, checkin); asset.reload(); }
    catch (reason) { setError(reason instanceof Error ? reason : new Error("Não foi possível registrar a devolução.")); }
  }
  if (asset.loading) return <Loading />;
  if (asset.error || !asset.data) return <ErrorState error={asset.error ?? new Error("Ativo não encontrado.")} onRetry={asset.reload} />;
  const data = asset.data;
  const activeCustody = data.assignments?.find((item) => item.kind === "CUSTODY" && !item.endedAt);
  return <section className={styles.page}>
    <Breadcrumb items={[{ label: "Inventário", to: "/inventory" }, { label: data.assetTag }]} />
    <header className={styles.header}><div><div className={styles.badges}><AssetStatusBadge status={data.status} /><AssetConditionBadge condition={data.condition} /><span>{data.operationalState}</span></div><h1>{data.assetTag} · {data.name}</h1><p>{data.type.name} · {[data.manufacturer, data.model].filter(Boolean).join(" ") || "Sem fabricante/modelo informado"}</p></div><div className={styles.headerActions}><LinkButton secondary to={`/inventory/${id}/edit`}>Editar</LinkButton>{!activeCustody && <LinkButton to={`/inventory/${id}/move`}>Movimentar</LinkButton>}</div></header>
    {error && <ErrorState error={error} />}
    <div className={styles.detailGrid}><Card><h2>Identificação e localização</h2><dl><dt>Série</dt><dd>{data.serialNumber ?? "—"}</dd><dt>Zona</dt><dd>{data.electoralZone ? `Zona ${data.electoralZone.number}` : "—"}</dd><dt>Local</dt><dd>{data.pollingPlace?.name ?? "Depósito central"}</dd><dt>Município</dt><dd>{data.pollingPlace?.city ?? data.electoralZone?.municipality ?? "—"}</dd></dl></Card><Card><h2>Custódia atual</h2>{activeCustody ? <dl><dt>Responsável</dt><dd>{activeCustody.assignedToName}</dd><dt>Finalidade</dt><dd>{activeCustody.purpose}</dd><dt>Destino</dt><dd>{activeCustody.destinationLabel}</dd><dt>Retorno previsto</dt><dd>{activeCustody.expectedReturnAt ? formatDateTime(activeCustody.expectedReturnAt) : "—"}</dd></dl> : <EmptyState title="Sem custódia ativa" description="O ativo não está em posse de um operador." />}</Card></div>
    {data.availableActions.checkOut && <Card><h2>Registrar retirada</h2><form className={styles.formGrid} onSubmit={submitCheckout}><Field label="Responsável"><Input required value={checkout.responsibleName} onChange={(event) => setCheckout((value) => ({ ...value, responsibleName: event.target.value }))} /></Field><Field label="Finalidade"><Input required value={checkout.purpose} onChange={(event) => setCheckout((value) => ({ ...value, purpose: event.target.value }))} /></Field><Field label="Origem"><Input required value={checkout.origin} onChange={(event) => setCheckout((value) => ({ ...value, origin: event.target.value }))} /></Field><Field label="Destino"><Input required value={checkout.destination} onChange={(event) => setCheckout((value) => ({ ...value, destination: event.target.value }))} /></Field><Field label="Retorno previsto"><Input type="datetime-local" value={checkout.expectedReturnAt} onChange={(event) => setCheckout((value) => ({ ...value, expectedReturnAt: event.target.value }))} /></Field><Field label="Condição na saída"><Select value={checkout.conditionOut} onChange={(event) => setCheckout((value) => ({ ...value, conditionOut: event.target.value as AssetCondition }))}>{ASSET_CONDITIONS.map((condition) => <option key={condition} value={condition}>{ASSET_CONDITION_LABELS[condition]}</option>)}</Select></Field><Button type="submit">Confirmar retirada</Button></form></Card>}
    {data.availableActions.checkIn && <Card><h2>Registrar devolução</h2><form className={styles.formGrid} onSubmit={submitCheckin}><Field label="Recebido por"><Input required value={checkin.receivedByName} onChange={(event) => setCheckin((value) => ({ ...value, receivedByName: event.target.value }))} /></Field><Field label="Local devolvido"><Input required value={checkin.returnedTo} onChange={(event) => setCheckin((value) => ({ ...value, returnedTo: event.target.value }))} /></Field><Field label="Condição no retorno"><Select value={checkin.conditionIn} onChange={(event) => setCheckin((value) => ({ ...value, conditionIn: event.target.value as AssetCondition }))}>{ASSET_CONDITIONS.map((condition) => <option key={condition} value={condition}>{ASSET_CONDITION_LABELS[condition]}</option>)}</Select></Field><label><input type="checkbox" checked={checkin.problemDetected} onChange={(event) => setCheckin((value) => ({ ...value, problemDetected: event.target.checked }))} /> Problema detectado</label><Field label="Observação"><Input value={checkin.notes} onChange={(event) => setCheckin((value) => ({ ...value, notes: event.target.value }))} /></Field><Button type="submit">Confirmar devolução</Button></form></Card>}
    <div className={styles.detailGrid}><Card><h2>Reservas</h2>{!data.reservations?.length ? <EmptyState title="Sem reservas" description="Nenhuma reserva para este ativo." /> : <ul className={styles.related}>{data.reservations.map((item) => <li key={item.id}><strong>{item.status}</strong><span>{item.requesterName} · {formatDateTime(item.startsAt)} até {formatDateTime(item.endsAt)}</span></li>)}</ul>}</Card><Card><h2>Manutenção</h2>{!data.maintenances?.length ? <EmptyState title="Sem manutenção" description="Nenhum serviço registrado." /> : <ul className={styles.related}>{data.maintenances.map((item) => <li key={item.id}><strong>{item.status}</strong><span>{item.type} · {item.description}</span></li>)}</ul>}</Card></div>
    <div className={styles.detailGrid}><Card><h2>Incidentes vinculados</h2>{!data.incidents?.length ? <EmptyState title="Sem incidentes ativos" description="Nenhum incidente aberto para este ativo." /> : <ul className={styles.related}>{data.incidents.map((incident) => <li key={incident.id}><Link to={`/incidents/${incident.id}`}>{incident.code}</Link><span>{incident.title}</span></li>)}</ul>}</Card><Card><h2>Histórico de custódia</h2>{!data.assignments?.length ? <EmptyState title="Sem registros" description="Nenhuma alocação ou custódia registrada." /> : <ul className={styles.related}>{data.assignments.filter((item) => item.kind === "CUSTODY").map((item) => <li key={item.id}><strong>{item.assignedToName ?? "Sem responsável"}</strong><span>{formatDateTime(item.assignedAt)} · {item.endedAt ? `devolvido em ${formatDateTime(item.endedAt)}` : "em aberto"}</span></li>)}</ul>}</Card></div>
    <Card><h2>Histórico de movimentações</h2>{!data.movements?.length ? <EmptyState title="Sem movimentações" description="O ativo ainda não possui histórico de transporte ou alocação." /> : <ol className={styles.movements}>{data.movements.map((movement) => <li key={movement.id}><time>{formatDateTime(movement.movedAt)}</time><strong>{movement.originLabel} → {movement.destinationLabel}</strong><span>{movement.reason} · {movement.responsibleName}</span></li>)}</ol>}</Card>
  </section>;
}
