import { useEffect, useState, type FormEvent } from "react";
import { ASSET_STATUSES, ASSET_STATUS_LABELS, type AssetStatus, type ElectoralZoneSummary, type PollingPlaceSummary } from "@eops/shared";
import { Button, ErrorState, Field, Input, Loading, Select } from "@eops/ui";
import { useNavigate, useParams } from "react-router-dom";
import { inventoryService } from "../services/inventoryService";
import styles from "../styles/inventory.module.css";

export function AssetMovePage() {
  const { id = "" } = useParams(); const navigate = useNavigate(); const [zones, setZones] = useState<ElectoralZoneSummary[]>([]); const [places, setPlaces] = useState<PollingPlaceSummary[]>([]);
  const [zoneId, setZoneId] = useState(""); const [placeId, setPlaceId] = useState(""); const [responsibleName, setResponsible] = useState(""); const [reason, setReason] = useState(""); const [statusAfter, setStatus] = useState<AssetStatus>("IN_USE"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<unknown>();
  useEffect(() => { void inventoryService.referenceLocations().then((data) => { setZones(data.zones); setPlaces(data.places); }).catch(setError).finally(() => setLoading(false)); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(undefined); try { await inventoryService.move(id, { toZoneId: zoneId || undefined, toPollingPlaceId: placeId || undefined, responsibleName, reason, statusAfter }); navigate(`/inventory/${id}`); } catch (cause) { setError(cause); } finally { setSaving(false); } }
  if (loading) return <Loading />;
  return <section className={styles.page}><h1>Movimentar ativo</h1><p>O registro da movimentação é imutável e permanecerá no histórico.</p>{error !== undefined && <ErrorState error={error} />}<form className={styles.form} onSubmit={(event) => void submit(event)}><div className={styles.formGrid}><Field label="Zona de destino"><Select value={zoneId} onChange={(event) => { setZoneId(event.target.value); setPlaceId(""); }}><option value="">Depósito central</option>{zones.map((zone) => <option key={zone.id} value={zone.id}>Zona {zone.number}</option>)}</Select></Field><Field label="Local de destino"><Select value={placeId} onChange={(event) => setPlaceId(event.target.value)}><option value="">Nenhum</option>{places.filter((place) => !zoneId || place.electoralZoneId === zoneId).map((place) => <option key={place.id} value={place.id}>{place.name}</option>)}</Select></Field><Field label="Status após movimentação"><Select value={statusAfter} onChange={(event) => setStatus(event.target.value as AssetStatus)}>{ASSET_STATUSES.map((status) => <option key={status} value={status}>{ASSET_STATUS_LABELS[status]}</option>)}</Select></Field><Field label="Responsável"><Input required value={responsibleName} onChange={(event) => setResponsible(event.target.value)} /></Field><Field label="Motivo"><Input required minLength={3} value={reason} onChange={(event) => setReason(event.target.value)} /></Field></div><Button disabled={saving} type="submit">{saving ? "Registrando…" : "Registrar movimentação"}</Button></form></section>;
}
