import { useEffect, useState, type FormEvent } from "react";
import { ASSET_CONDITIONS, ASSET_CONDITION_LABELS, ASSET_STATUSES, ASSET_STATUS_LABELS, type AssetCondition, type AssetStatus, type AssetTypeSummary } from "@eops/shared/inventory";
import { type ElectoralZoneSummary, type PollingPlaceSummary } from "@eops/shared/elections";
import { Button, ErrorState, Field, Input, Loading, Select } from "@eops/ui";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { inventoryService } from "../services/inventoryService";
import styles from "../styles/inventory.module.css";

interface State { assetTag: string; name: string; typeId: string; serialNumber: string; manufacturer: string; model: string; status: AssetStatus; condition: AssetCondition; electoralZoneId: string; pollingPlaceId: string; }
const empty: State = { assetTag: "", name: "", typeId: "", serialNumber: "", manufacturer: "", model: "", status: "AVAILABLE", condition: "GOOD", electoralZoneId: "", pollingPlaceId: "" };
export function AssetFormPage() {
  const { id } = useParams(); const [params] = useSearchParams(); const navigate = useNavigate();
  const [form, setForm] = useState<State>({ ...empty, pollingPlaceId: params.get("pollingPlaceId") ?? "" });
  const [types, setTypes] = useState<AssetTypeSummary[]>([]); const [zones, setZones] = useState<ElectoralZoneSummary[]>([]); const [places, setPlaces] = useState<PollingPlaceSummary[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<unknown>(); const [saving, setSaving] = useState(false);
  useEffect(() => { void (async () => { try { const [typeData, locations, asset] = await Promise.all([inventoryService.types(), inventoryService.referenceLocations(), id ? inventoryService.get(id) : Promise.resolve(null)]); setTypes(typeData.filter((type) => type.active)); setZones(locations.zones); setPlaces(locations.places); if (asset) setForm({ assetTag: asset.assetTag, name: asset.name, typeId: asset.typeId, serialNumber: asset.serialNumber ?? "", manufacturer: asset.manufacturer ?? "", model: asset.model ?? "", status: asset.status, condition: asset.condition, electoralZoneId: asset.electoralZoneId ?? "", pollingPlaceId: asset.pollingPlaceId ?? "" }); else { const place = locations.places.find((item) => item.id === params.get("pollingPlaceId")); if (place) setForm((current) => ({ ...current, electoralZoneId: place.electoralZoneId })); } } catch (cause) { setError(cause); } finally { setLoading(false); } })(); }, [id]);
  const set = (key: keyof State, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(undefined); try { const payload = { ...form, serialNumber: form.serialNumber || undefined, manufacturer: form.manufacturer || undefined, model: form.model || undefined, electoralZoneId: form.electoralZoneId || undefined, pollingPlaceId: form.pollingPlaceId || undefined }; const saved = id ? await inventoryService.update(id, payload) : await inventoryService.create(payload); navigate(`/inventory/${saved.id}`); } catch (cause) { setError(cause); } finally { setSaving(false); } }
  if (loading) return <Loading />;
  return <section className={styles.page}><h1>{id ? "Editar ativo" : "Novo ativo"}</h1>{error !== undefined && <ErrorState error={error} />}<form className={styles.form} onSubmit={(event) => void submit(event)}><div className={styles.formGrid}>
    <Field label="Patrimônio"><Input required disabled={Boolean(id)} value={form.assetTag} onChange={(event) => set("assetTag", event.target.value)} /></Field><Field label="Nome"><Input required value={form.name} onChange={(event) => set("name", event.target.value)} /></Field><Field label="Tipo"><Select required value={form.typeId} onChange={(event) => set("typeId", event.target.value)}><option value="">Selecione</option>{types.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</Select></Field>
    <Field label="Número de série"><Input value={form.serialNumber} onChange={(event) => set("serialNumber", event.target.value)} /></Field><Field label="Fabricante"><Input value={form.manufacturer} onChange={(event) => set("manufacturer", event.target.value)} /></Field><Field label="Modelo"><Input value={form.model} onChange={(event) => set("model", event.target.value)} /></Field>
    <Field label="Status"><Select value={form.status} onChange={(event) => set("status", event.target.value)}>{ASSET_STATUSES.map((item) => <option key={item} value={item}>{ASSET_STATUS_LABELS[item]}</option>)}</Select></Field><Field label="Condição"><Select value={form.condition} onChange={(event) => set("condition", event.target.value)}>{ASSET_CONDITIONS.map((item) => <option key={item} value={item}>{ASSET_CONDITION_LABELS[item]}</option>)}</Select></Field>
    {!id && <><Field label="Zona"><Select value={form.electoralZoneId} onChange={(event) => setForm((current) => ({ ...current, electoralZoneId: event.target.value, pollingPlaceId: "" }))}><option value="">Depósito central</option>{zones.map((zone) => <option key={zone.id} value={zone.id}>Zona {zone.number}</option>)}</Select></Field><Field label="Local"><Select value={form.pollingPlaceId} onChange={(event) => set("pollingPlaceId", event.target.value)}><option value="">Nenhum</option>{places.filter((place) => !form.electoralZoneId || place.electoralZoneId === form.electoralZoneId).map((place) => <option key={place.id} value={place.id}>{place.name}</option>)}</Select></Field></>}
  </div><Button disabled={saving} type="submit">{saving ? "Salvando…" : "Salvar ativo"}</Button></form></section>;
}
