import { useState, type FormEvent } from "react";
import { Badge, Button, Card, EmptyState, ErrorState, Field, Input, LinkButton, Loading, Select, useAsync } from "@eops/ui";
import { useParams } from "react-router-dom";
import { transmissionService } from "../../services/transmissionService";
import { useHasPermission } from "../hooks/usePermissions";
import { CONNECTIVITY_LABELS, DEADLINE_STATE_LABELS, TRANSMISSION_LABELS, deriveDeadlineState, type AlertStatus, type AttemptResult, type ConnectivityStatus } from "../../types";
import styles from "../../styles/overview.module.css";

const deadlineTone = (state: string) => state === "OVERDUE" ? "danger" : state === "DUE_SOON" ? "warning" : state === "COMPLETED" ? "success" : "neutral";

export function TransmissionPointDetailPage() {
  const { id = "" } = useParams();
  const point = useAsync(() => transmissionService.get(id), [id]);
  const history = useAsync(() => transmissionService.connectivityHistory(id), [id]);
  const { allowed: canManage } = useHasPermission("transmission.manage");
  const [connectivity, setConnectivity] = useState<{ connectivity: ConnectivityStatus; latencyMs: string; connectionMethod: string }>({ connectivity: "ONLINE", latencyMs: "", connectionMethod: "" });
  const [attempt, setAttempt] = useState<{ result: AttemptResult; error: string }>({ result: "SUCCESS", error: "" });
  const [error, setError] = useState<Error>();
  async function saveConnectivity(event: FormEvent) { event.preventDefault(); try { await transmissionService.connectivity(id, { connectivity: connectivity.connectivity, latencyMs: connectivity.latencyMs ? Number(connectivity.latencyMs) : undefined, connectionMethod: connectivity.connectionMethod || undefined }); point.reload(); history.reload(); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Falha ao registrar conectividade.")); } }
  async function registerAttempt(event: FormEvent) { event.preventDefault(); const endedAt = new Date(); const startedAt = new Date(endedAt.getTime() - 30_000); try { await transmissionService.attempt(id, { startedAt: startedAt.toISOString(), endedAt: endedAt.toISOString(), result: attempt.result, error: attempt.result === "SUCCESS" ? undefined : attempt.error }); setAttempt({ result: "SUCCESS", error: "" }); point.reload(); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Falha ao registrar tentativa.")); } }
  async function changeAlert(alertId: string, status: AlertStatus) { try { await transmissionService.updateAlert(alertId, status); point.reload(); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Falha ao atualizar alerta.")); } }
  async function requestRetry() { try { await transmissionService.retry(id, "Retry manual pelo operador."); point.reload(); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Falha ao solicitar retry.")); } }
  if (point.loading) return <Loading label="Carregando ponto…" />;
  if (point.error || !point.data) return <ErrorState error={point.error ?? new Error("Ponto não encontrado.")} />;
  const data = point.data;
  const deadlineState = deriveDeadlineState(data.status, data.operationalDeadline);
  return <section className={styles.page}><header className={styles.header}><div><span className={styles.tag}>{data.identification}</span><h1>{data.pollingPlace.name}</h1><p>Zona {data.electoralZone.number} · {data.election.name}</p></div><div className={styles.actions}><LinkButton secondary to="/transmission">Voltar ao dashboard</LinkButton>{canManage && <Button onClick={() => void requestRetry()}>Solicitar retry</Button>}</div></header>{error && <ErrorState error={error} />}
    <div className={styles.metrics}><Card><span>Status</span><strong>{TRANSMISSION_LABELS[data.status]}</strong></Card><Card><span>Estado do prazo</span><strong><Badge tone={deadlineTone(deadlineState)}>{DEADLINE_STATE_LABELS[deadlineState]}</Badge></strong><small>{data.operationalDeadline ? new Date(data.operationalDeadline).toLocaleString("pt-BR") : "Sem limite definido"}</small></Card><Card><span>Conectividade</span><strong>{CONNECTIVITY_LABELS[data.connectivity]}</strong></Card><Card><span>Prioridade</span><strong>P{data.priority}</strong></Card><Card><span>Tentativas</span><strong>{data.attemptCount}</strong><small>{history.data ? `${history.data.failureStreak} falhas consecutivas` : ""}</small></Card><Card><span>Latência</span><strong>{data.latencyMs != null ? `${data.latencyMs} ms` : "—"}</strong></Card><Card><span>Última atividade</span><strong>{data.lastActivity ? new Date(data.lastActivity).toLocaleTimeString("pt-BR") : "—"}</strong></Card><Card><span>Último sucesso</span><strong>{history.data?.lastSuccessAt ? new Date(history.data.lastSuccessAt).toLocaleString("pt-BR") : "—"}</strong></Card></div>
    <div className={styles.columns}><Card><h2>Registrar conectividade</h2><form className={styles.form} onSubmit={saveConnectivity}><Field label="Estado"><Select value={connectivity.connectivity} onChange={(event) => setConnectivity((value) => ({ ...value, connectivity: event.target.value as ConnectivityStatus }))}><option value="ONLINE">Online</option><option value="DEGRADED">Degradada</option><option value="OFFLINE">Offline</option><option value="UNKNOWN">Desconhecida</option></Select></Field><Field label="Latência (ms)"><Input min="0" type="number" value={connectivity.latencyMs} onChange={(event) => setConnectivity((value) => ({ ...value, latencyMs: event.target.value }))} /></Field><Field label="Método"><Input value={connectivity.connectionMethod} onChange={(event) => setConnectivity((value) => ({ ...value, connectionMethod: event.target.value }))} /></Field><Button type="submit">Registrar verificação</Button></form></Card><Card><h2>Registrar tentativa</h2><form className={styles.form} onSubmit={registerAttempt}><Field label="Resultado"><Select value={attempt.result} onChange={(event) => setAttempt((value) => ({ ...value, result: event.target.value as AttemptResult }))}><option value="SUCCESS">Sucesso</option><option value="FAILED">Falha</option><option value="TIMEOUT">Timeout</option><option value="CANCELLED">Cancelada</option></Select></Field>{attempt.result !== "SUCCESS" && <Field label="Erro"><Input required value={attempt.error} onChange={(event) => setAttempt((value) => ({ ...value, error: event.target.value }))} /></Field>}<Button type="submit">Salvar tentativa</Button></form></Card></div>
    <Card><h2>Alertas</h2>{data.alerts.length === 0 ? <EmptyState title="Sem alertas" description="Nenhum alerta registrado para este ponto." /> : <div className={styles.alerts}>{data.alerts.map((alert) => <article key={alert.id}><div className={styles.alertHead}><Badge tone={alert.status === "RESOLVED" ? "success" : alert.status === "ACKNOWLEDGED" ? "warning" : "danger"}>{alert.type.replaceAll("_", " ")}</Badge><span className={styles.alertState}>{alert.status === "OPEN" ? "Aberto" : alert.status === "ACKNOWLEDGED" ? "Reconhecido" : "Resolvido"}</span></div><p>{alert.message}</p>{alert.notes && <small>Nota: {alert.notes}</small>}<small>{new Date(alert.createdAt).toLocaleString("pt-BR")}{alert.acknowledgedAt ? ` · reconhecido ${new Date(alert.acknowledgedAt).toLocaleString("pt-BR")}` : ""}{alert.resolvedAt ? ` · resolvido ${new Date(alert.resolvedAt).toLocaleString("pt-BR")}` : ""}</small>{canManage && alert.status !== "RESOLVED" && <div className={styles.actions}>{alert.status === "OPEN" && <Button secondary onClick={() => void changeAlert(alert.id, "ACKNOWLEDGED")}>Reconhecer</Button>}<Button onClick={() => void changeAlert(alert.id, "RESOLVED")}>Resolver</Button></div>}</article>)}</div>}</Card>
    <Card><h2>Histórico de conectividade</h2>{history.loading && <Loading label="Carregando histórico…" />}{history.data && (history.data.entries.length === 0 ? <EmptyState title="Sem registros" description="Nenhuma mudança de conectividade registrada." /> : <div className={styles.tableWrap}><table><thead><tr><th>Momento</th><th>Conectividade</th><th>Latência</th></tr></thead><tbody>{history.data.entries.slice().reverse().map((entry) => <tr key={entry.at}><td>{new Date(entry.at).toLocaleString("pt-BR")}</td><td><Badge tone={entry.connectivity === "ONLINE" ? "success" : entry.connectivity === "OFFLINE" ? "danger" : "warning"}>{CONNECTIVITY_LABELS[entry.connectivity]}</Badge></td><td>{entry.latencyMs != null ? `${entry.latencyMs} ms` : "—"}</td></tr>)}</tbody></table></div>)}</Card>
    <Card><h2>Tentativas</h2>{data.attempts.length === 0 ? <p>Nenhuma tentativa registrada.</p> : <div className={styles.tableWrap}><table><thead><tr><th>#</th><th>Início</th><th>Fim</th><th>Duração</th><th>Resultado</th><th>Erro</th></tr></thead><tbody>{data.attempts.map((item) => <tr key={item.id}><td>{item.number}</td><td>{new Date(item.startedAt).toLocaleString("pt-BR")}</td><td>{new Date(item.endedAt).toLocaleString("pt-BR")}</td><td>{Math.round(item.durationMs / 1000)}s</td><td><Badge tone={item.result === "SUCCESS" ? "success" : "danger"}>{item.result}</Badge></td><td>{item.error || "—"}</td></tr>)}</tbody></table></div>}</Card>
    <Card><h2>Timeline</h2><ol className={styles.timeline}>{data.timeline.map((event) => <li key={event.id}><time>{new Date(event.createdAt).toLocaleString("pt-BR")}</time><div><strong>{event.type.replaceAll("_", " ")}</strong><p>{event.message}</p></div></li>)}</ol></Card>
  </section>;
}
