import { useState } from "react";
import { Badge, Card, EmptyState, ErrorState, LinkButton, Loading, Select, useAsync } from "@eops/ui";
import { Link } from "react-router-dom";
import { transmissionService } from "../../services/transmissionService";
import { CONNECTIVITY_LABELS, DEADLINE_STATE_LABELS, TRANSMISSION_LABELS, type ConnectivityStatus, type DeadlineState, type TransmissionFilters, type TransmissionStatus } from "../../types";
import styles from "../../styles/overview.module.css";

const statusTone = (status: TransmissionStatus) => status === "SUCCESS" ? "success" : ["FAILED", "OFFLINE"].includes(status) ? "danger" : ["TRANSMITTING", "RETRYING"].includes(status) ? "warning" : "neutral";
const deadlineTone = (state: DeadlineState) => state === "OVERDUE" ? "danger" : state === "DUE_SOON" ? "warning" : state === "COMPLETED" ? "success" : "neutral";
const connectivityTone = (connectivity: ConnectivityStatus) => connectivity === "ONLINE" ? "success" : connectivity === "OFFLINE" ? "danger" : connectivity === "DEGRADED" ? "warning" : "neutral";

export function TransmissionNocPage() {
  const [filters, setFilters] = useState<TransmissionFilters>({});
  const noc = useAsync(() => transmissionService.noc(filters), [JSON.stringify(filters)]);
  const references = useAsync(transmissionService.references, []);
  const change = (key: keyof TransmissionFilters, value: string) => setFilters((current) => ({ ...current, [key]: value || undefined }));
  const zones = references.data?.zones.filter((zone) => !filters.electionId || zone.electionId === filters.electionId) ?? [];
  const places = references.data?.places.filter((place) => !filters.zoneId || place.electoralZoneId === filters.zoneId) ?? [];
  const zoneNumber = (zoneId: string) => references.data?.zones.find((zone) => zone.id === zoneId)?.number;
  if (noc.loading) return <Loading label="Carregando visão NOC…" />;
  if (noc.error || !noc.data) return <ErrorState error={noc.error ?? new Error("Não foi possível carregar a visão NOC.")} onRetry={noc.reload} />;
  const data = noc.data;
  return <section className={styles.page}><header className={styles.header}><div><span className={styles.tag}>NOC · TRANSMISSÃO</span><h1>Centro de operações de transmissão</h1><p>Totais, taxas, prazo derivado, latência e pontos que exigem atenção.</p></div><LinkButton to="/transmission">Voltar ao dashboard</LinkButton></header>
    <div className={styles.filters}><Select aria-label="Pleito" value={filters.electionId ?? ""} onChange={(event) => change("electionId", event.target.value)}><option value="">Todos os pleitos</option>{references.data?.elections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="Zona" value={filters.zoneId ?? ""} onChange={(event) => change("zoneId", event.target.value)}><option value="">Todas as zonas</option>{zones.map((item) => <option key={item.id} value={item.id}>Zona {item.number} · {item.name}</option>)}</Select><Select aria-label="Local" value={filters.pollingPlaceId ?? ""} onChange={(event) => change("pollingPlaceId", event.target.value)}><option value="">Todos os locais</option>{places.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></div>
    <div className={styles.metrics}><Card><span>Total</span><strong>{data.totals.total}</strong><small>{data.totals.transmitting} transmitindo</small></Card><Card><span>Concluídas</span><strong>{data.totals.success}</strong><small>{data.rates.successRate}% sucesso</small></Card><Card><span>Na fila</span><strong>{data.totals.queued}</strong></Card><Card><span>Falhas</span><strong>{data.totals.failed}</strong><small>{data.rates.failureRate}% falha</small></Card><Card><span>Offline</span><strong>{data.totals.offline}</strong></Card><Card><span>Risco de prazo</span><strong>{data.risk.deadlineRisk}</strong><small>{data.risk.overdue} atrasados · {data.risk.dueSoon} próximos</small></Card><Card><span>Latência média</span><strong>{data.latency.averageLatencyMs} ms</strong></Card><Card><span>Tentativas hoje</span><strong>{data.volume.attemptsToday}</strong></Card></div>
    <div className={styles.columns}><Card><div className={styles.sectionTitle}><h2>Por zona</h2><span>{data.byZone.length} zonas</span></div>{data.byZone.length === 0 ? <EmptyState title="Sem zonas" description="Nenhum ponto de transmissão no filtro atual." /> : <div className={styles.tableWrap}><table><thead><tr><th>Zona</th><th>Total</th><th>Sucesso</th><th>Falhas</th><th>Offline</th><th>Risco de prazo</th><th>Taxa</th><th>Latência</th></tr></thead><tbody>{data.byZone.map((zone) => <tr key={zone.zoneId}><td>Zona {zone.number}<small>{zone.name}</small></td><td>{zone.total}</td><td>{zone.success}</td><td>{zone.failed}</td><td>{zone.offline}</td><td>{zone.deadlineRisk}</td><td>{zone.successRate}%</td><td>{zone.averageLatencyMs} ms</td></tr>)}</tbody></table></div>}</Card>
      <Card><div className={styles.sectionTitle}><h2>Exige atenção</h2><span>{data.needsAttention.length}</span></div>{data.needsAttention.length === 0 ? <EmptyState title="Nada crítico" description="Nenhum ponto atrasado, próximo do prazo, falho ou offline." /> : <div className={styles.attention}>{data.needsAttention.map((point) => <Link key={point.id} to={`/transmission/${point.id}`}><strong>{point.identification}</strong><span>{point.pollingPlaceName} · Zona {point.zoneNumber}</span><div><Badge tone={statusTone(point.status)}>{TRANSMISSION_LABELS[point.status]}</Badge><Badge tone={deadlineTone(point.deadlineState)}>{DEADLINE_STATE_LABELS[point.deadlineState]}</Badge><Badge tone={connectivityTone(point.connectivity)}>{CONNECTIVITY_LABELS[point.connectivity]}</Badge></div></Link>)}</div>}</Card></div>
    <Card><h2>Por local de votação</h2>{data.byPlace.length === 0 ? <EmptyState title="Sem locais" description="Nenhum ponto de transmissão no filtro atual." /> : <div className={styles.tableWrap}><table><thead><tr><th>Local</th><th>Total</th><th>Sucesso</th><th>Falhas</th><th>Offline</th><th>Risco de prazo</th></tr></thead><tbody>{data.byPlace.map((place) => <tr key={place.pollingPlaceId}><td>{place.name}<small>{zoneNumber(place.zoneId) ? `Zona ${zoneNumber(place.zoneId)}` : ""}</small></td><td>{place.total}</td><td>{place.success}</td><td>{place.failed}</td><td>{place.offline}</td><td>{place.deadlineRisk}</td></tr>)}</tbody></table></div>}</Card>
  </section>;
}
