import { useState, type FormEvent } from "react";
import { Button, ErrorState, Field, Input, Loading, Select, useAsync } from "@eops/ui";
import { useNavigate } from "react-router-dom";
import { transmissionService } from "../../services/transmissionService";
import type { TransmissionInput } from "../../types";
import styles from "../../styles/overview.module.css";

type FormState = Omit<TransmissionInput, "priority"> & { priority: string };
const empty: FormState = { electionId: "", electoralZoneId: "", pollingPlaceId: "", identification: "", status: "QUEUED", connectivity: "UNKNOWN", observations: "", priority: "3", queuedAt: new Date().toISOString().slice(0, 16), operationalDeadline: "", connectionMethod: "" };

export function TransmissionPointFormPage() {
  const navigate = useNavigate();
  const references = useAsync(transmissionService.references, []);
  const [form, setForm] = useState<FormState>(empty);
  const [error, setError] = useState<Error>(); const [saving, setSaving] = useState(false);
  const set = (key: keyof FormState, value: string) => setForm((state) => ({ ...state, [key]: value }));
  const zones = references.data?.zones.filter((zone) => zone.electionId === form.electionId) ?? [];
  const places = references.data?.places.filter((place) => place.electoralZoneId === form.electoralZoneId) ?? [];
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(undefined); try { const point = await transmissionService.create({ ...form, priority: Number(form.priority), queuedAt: form.queuedAt ? new Date(form.queuedAt).toISOString() : undefined, operationalDeadline: form.operationalDeadline ? new Date(form.operationalDeadline).toISOString() : undefined }); navigate(`/transmission/${point.id}`); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Falha ao cadastrar ponto.")); } finally { setSaving(false); } }
  if (references.loading) return <Loading label="Carregando referências…" />;
  return <section className={styles.page}><header className={styles.header}><div><span className={styles.tag}>TRANSMISSÃO</span><h1>Novo ponto de transmissão</h1><p>Cadastre localização, prioridade, conectividade e limite operacional.</p></div></header>{error && <ErrorState error={error} />}<form className={styles.form} onSubmit={submit}><div className={styles.formGrid}><Field label="Identificação"><Input required value={form.identification} onChange={(event) => set("identification", event.target.value)} /></Field><Field label="Pleito"><Select required value={form.electionId} onChange={(event) => set("electionId", event.target.value)}><option value="">Selecione</option>{references.data?.elections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Zona"><Select required value={form.electoralZoneId} onChange={(event) => set("electoralZoneId", event.target.value)}><option value="">Selecione</option>{zones.map((item) => <option key={item.id} value={item.id}>Zona {item.number} · {item.name}</option>)}</Select></Field><Field label="Local"><Select required value={form.pollingPlaceId} onChange={(event) => set("pollingPlaceId", event.target.value)}><option value="">Selecione</option>{places.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Prioridade (1 é maior)"><Input required min="1" max="5" type="number" value={form.priority} onChange={(event) => set("priority", event.target.value)} /></Field><Field label="Conectividade"><Select value={form.connectivity} onChange={(event) => set("connectivity", event.target.value)}><option value="UNKNOWN">Desconhecida</option><option value="ONLINE">Online</option><option value="DEGRADED">Degradada</option><option value="OFFLINE">Offline</option></Select></Field><Field label="Entrada na fila"><Input type="datetime-local" value={form.queuedAt} onChange={(event) => set("queuedAt", event.target.value)} /></Field><Field label="Limite operacional"><Input type="datetime-local" value={form.operationalDeadline} onChange={(event) => set("operationalDeadline", event.target.value)} /></Field><Field label="Método/conexão"><Input placeholder="Fibra, 4G, satélite…" value={form.connectionMethod} onChange={(event) => set("connectionMethod", event.target.value)} /></Field></div><Field label="Observações"><textarea className={styles.textarea} value={form.observations} onChange={(event) => set("observations", event.target.value)} /></Field><Button disabled={saving} type="submit">{saving ? "Salvando…" : "Cadastrar ponto"}</Button></form></section>;
}
