import { useState, type FormEvent } from "react";
import { Badge, Button, Card, ErrorState, Field, Input, LinkButton, Loading, Select, useAsync } from "@eops/ui";
import { useParams } from "react-router-dom";
import { transmissionService } from "../../services/transmissionService";
import { CONNECTIVITY_LABELS, TRANSMISSION_LABELS, type AttemptResult, type ConnectivityStatus } from "../../types";
import styles from "../../styles/overview.module.css";

export function TransmissionPointDetailPage() {
  const { id = "" } = useParams();
  const point = useAsync(() => transmissionService.get(id), [id]);
  const [connectivity, setConnectivity] = useState<{ connectivity: ConnectivityStatus; latencyMs: string; connectionMethod: string }>({ connectivity: "ONLINE", latencyMs: "", connectionMethod: "" });
  const [attempt, setAttempt] = useState<{ result: AttemptResult; error: string }>({ result: "SUCCESS", error: "" });
  const [error, setError] = useState<Error>();
  async function saveConnectivity(event: FormEvent) { event.preventDefault(); try { await transmissionService.connectivity(id, { connectivity: connectivity.connectivity, latencyMs: connectivity.latencyMs ? Number(connectivity.latencyMs) : undefined, connectionMethod: connectivity.connectionMethod || undefined }); point.reload(); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Falha ao registrar conectividade.")); } }
  async function registerAttempt(event: FormEvent) { event.preventDefault(); const endedAt = new Date(); const startedAt = new Date(endedAt.getTime() - 30_000); try { await transmissionService.attempt(id, { startedAt: startedAt.toISOString(), endedAt: endedAt.toISOString(), result: attempt.result, error: attempt.result === "SUCCESS" ? undefined : attempt.error }); setAttempt({ result: "SUCCESS", error: "" }); point.reload(); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Falha ao registrar tentativa.")); } }
  if (point.loading) return <Loading label="Carregando ponto…" />;
  if (point.error || !point.data) return <ErrorState error={point.error ?? new Error("Ponto não encontrado.")} />;
  const data = point.data;
  return <section className={styles.page}><header className={styles.header}><div><span className={styles.tag}>{data.identification}</span><h1>{data.pollingPlace.name}</h1><p>Zona {data.electoralZone.number} · {data.election.name}</p></div><LinkButton to="/transmission">Voltar ao dashboard</LinkButton></header>{error && <ErrorState error={error} />}
    <div className={styles.metrics}><Card><span>Status</span><strong>{TRANSMISSION_LABELS[data.status]}</strong></Card><Card><span>Conectividade</span><strong>{CONNECTIVITY_LABELS[data.connectivity]}</strong></Card><Card><span>Prioridade</span><strong>P{data.priority}</strong></Card><Card><span>Tentativas</span><strong>{data.attemptCount}</strong></Card><Card><span>Latência</span><strong>{data.latencyMs != null ? `${data.latencyMs} ms` : "—"}</strong></Card><Card><span>Última atividade</span><strong>{data.lastActivity ? new Date(data.lastActivity).toLocaleTimeString("pt-BR") : "—"}</strong></Card></div>
    <div className={styles.columns}><Card><h2>Registrar conectividade</h2><form className={styles.form} onSubmit={saveConnectivity}><Field label="Estado"><Select value={connectivity.connectivity} onChange={(event) => setConnectivity((value) => ({ ...value, connectivity: event.target.value as ConnectivityStatus }))}><option value="ONLINE">Online</option><option value="DEGRADED">Degradada</option><option value="OFFLINE">Offline</option><option value="UNKNOWN">Desconhecida</option></Select></Field><Field label="Latência (ms)"><Input min="0" type="number" value={connectivity.latencyMs} onChange={(event) => setConnectivity((value) => ({ ...value, latencyMs: event.target.value }))} /></Field><Field label="Método"><Input value={connectivity.connectionMethod} onChange={(event) => setConnectivity((value) => ({ ...value, connectionMethod: event.target.value }))} /></Field><Button type="submit">Registrar verificação</Button></form></Card><Card><h2>Registrar tentativa</h2><form className={styles.form} onSubmit={registerAttempt}><Field label="Resultado"><Select value={attempt.result} onChange={(event) => setAttempt((value) => ({ ...value, result: event.target.value as AttemptResult }))}><option value="SUCCESS">Sucesso</option><option value="FAILED">Falha</option><option value="TIMEOUT">Timeout</option><option value="CANCELLED">Cancelada</option></Select></Field>{attempt.result !== "SUCCESS" && <Field label="Erro"><Input required value={attempt.error} onChange={(event) => setAttempt((value) => ({ ...value, error: event.target.value }))} /></Field>}<Button type="submit">Salvar tentativa</Button></form></Card></div>
    <Card><h2>Tentativas</h2>{data.attempts.length === 0 ? <p>Nenhuma tentativa registrada.</p> : <div className={styles.tableWrap}><table><thead><tr><th>#</th><th>Início</th><th>Fim</th><th>Duração</th><th>Resultado</th><th>Erro</th></tr></thead><tbody>{data.attempts.map((item) => <tr key={item.id}><td>{item.number}</td><td>{new Date(item.startedAt).toLocaleString("pt-BR")}</td><td>{new Date(item.endedAt).toLocaleString("pt-BR")}</td><td>{Math.round(item.durationMs / 1000)}s</td><td><Badge tone={item.result === "SUCCESS" ? "success" : "danger"}>{item.result}</Badge></td><td>{item.error || "—"}</td></tr>)}</tbody></table></div>}</Card>
    <Card><h2>Timeline</h2><ol className={styles.timeline}>{data.timeline.map((event) => <li key={event.id}><time>{new Date(event.createdAt).toLocaleString("pt-BR")}</time><div><strong>{event.type.replaceAll("_", " ")}</strong><p>{event.message}</p></div></li>)}</ol></Card>
  </section>;
}
