import { useState } from "react";
import { Badge, Button, Card, EmptyState, ErrorState, LinkButton, Loading, Select, useAsync } from "@eops/ui";
import { Link } from "react-router-dom";
import { transmissionService } from "../../services/transmissionService";
import { CONNECTIVITY_LABELS, TRANSMISSION_LABELS, TRANSMISSION_STATUSES, type TransmissionFilters, type TransmissionStatus } from "../../types";
import styles from "../../styles/overview.module.css";

const tone = (status: TransmissionStatus) => status === "SUCCESS" ? "success" : ["FAILED", "OFFLINE"].includes(status) ? "danger" : ["TRANSMITTING", "RETRYING"].includes(status) ? "warning" : "neutral";

export function TransmissionDashboardPage() {
  const [filters, setFilters] = useState<TransmissionFilters>({});
  const points = useAsync(() => transmissionService.list(filters), [JSON.stringify(filters)]);
  const queue = useAsync(() => transmissionService.queue(filters), [JSON.stringify(filters)]);
  const dashboard = useAsync(() => transmissionService.dashboard(filters), [JSON.stringify(filters)]);
  const alerts = useAsync(() => transmissionService.alerts({ electionId: filters.electionId, zoneId: filters.zoneId, pollingPlaceId: filters.pollingPlaceId }), [JSON.stringify(filters)]);
  const sla = useAsync(() => transmissionService.sla({ electionId: filters.electionId, zoneId: filters.zoneId, pollingPlaceId: filters.pollingPlaceId }), [JSON.stringify(filters)]);
  const references = useAsync(transmissionService.references, []);
  const change = (key: keyof TransmissionFilters, value: string) => setFilters((current) => ({ ...current, [key]: value || undefined }));
  const zones = references.data?.zones.filter((zone) => !filters.electionId || zone.electionId === filters.electionId) ?? [];
  const places = references.data?.places.filter((place) => !filters.zoneId || place.electoralZoneId === filters.zoneId) ?? [];
  async function acknowledge(id: string) { await transmissionService.updateAlert(id, "ACKNOWLEDGED"); alerts.reload(); }
  const error = points.error ?? queue.error ?? dashboard.error ?? alerts.error ?? sla.error;
  return <section className={styles.page}><header className={styles.header}><div><span className={styles.tag}>MONITORAMENTO</span><h1>Monitor de Transmissão</h1><p>Fila operacional, conectividade, SLA, tentativas, progresso e alertas por zona e local.</p></div><div className={styles.actions}><LinkButton secondary to="/transmission/noc">Visão NOC</LinkButton><LinkButton secondary to="/transmission/analytics">SLA e analytics</LinkButton><LinkButton secondary to="/transmission/providers">Provedores</LinkButton><LinkButton to="/transmission/new">Novo ponto</LinkButton></div></header>
    <div className={styles.filters}><Select aria-label="Pleito" value={filters.electionId ?? ""} onChange={(event) => change("electionId", event.target.value)}><option value="">Todos os pleitos</option>{references.data?.elections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="Zona" value={filters.zoneId ?? ""} onChange={(event) => change("zoneId", event.target.value)}><option value="">Todas as zonas</option>{zones.map((item) => <option key={item.id} value={item.id}>Zona {item.number} · {item.name}</option>)}</Select><Select aria-label="Local" value={filters.pollingPlaceId ?? ""} onChange={(event) => change("pollingPlaceId", event.target.value)}><option value="">Todos os locais</option>{places.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="Status" value={filters.status ?? ""} onChange={(event) => change("status", event.target.value)}><option value="">Todos os status</option>{TRANSMISSION_STATUSES.map((status) => <option key={status} value={status}>{TRANSMISSION_LABELS[status]}</option>)}</Select></div>
    {dashboard.data && <><div className={styles.progress}><div style={{ width: `${dashboard.data.completionPercentage}%` }} /></div><div className={styles.metrics}><Card><span>Esperados</span><strong>{dashboard.data.totalExpected}</strong></Card><Card><span>Concluídos</span><strong>{dashboard.data.completed}</strong><small>{dashboard.data.completionPercentage}%</small></Card><Card><span>Pendentes</span><strong>{dashboard.data.pending}</strong></Card><Card><span>Transmitindo</span><strong>{dashboard.data.transmitting}</strong></Card><Card><span>Falhas</span><strong>{dashboard.data.failed}</strong></Card><Card><span>Zonas completas</span><strong>{dashboard.data.completeZones}</strong><small>{dashboard.data.zonesWithFailure} com falha</small></Card><Card><span>Taxa de sucesso</span><strong>{dashboard.data.successRate}%</strong></Card><Card><span>Taxa de falha</span><strong>{dashboard.data.failureRate}%</strong></Card><Card><span>Risco de prazo</span><strong>{dashboard.data.deadlineRisk}</strong></Card><Card><span>Locais offline</span><strong>{dashboard.data.offlineLocations}</strong></Card><Card><span>Latência média</span><strong>{dashboard.data.averageLatencyMs} ms</strong></Card><Card><span>Tentativas hoje</span><strong>{dashboard.data.attemptsToday}</strong></Card></div></>}
    {(sla.data) && <div className={styles.slaBand}><div><span>Uptime da janela</span><strong className={(sla.data.uptimePercent ?? 100) < 99 ? styles.riskHigh : styles.riskOk}>{sla.data.uptimePercent === null ? "—" : `${sla.data.uptimePercent}%`}</strong><small className={styles.muted}>{sla.data.observedMinutes} min observados</small></div><div><span>Downtime</span><strong className={sla.data.downtimeMinutes > 0 ? styles.riskHigh : undefined}>{sla.data.downtimeMinutes} min</strong><small className={styles.muted}>{sla.data.degradedMinutes} min degradado</small></div><div><span>Sem leitura</span><strong className={styles.warnValue}>{sla.data.unknownMinutes} min</strong><small className={styles.muted}>UNKNOWN fora do uptime</small></div><div><span>Risco de prazo</span><strong className={styles.infoValue}>{sla.data.deadlineRiskPercent === null ? "—" : `${sla.data.deadlineRiskPercent}%`}</strong><small className={styles.muted}>{sla.data.recoverySeconds === null ? "sem recuperação medida" : `recuperação média ${sla.data.recoverySeconds}s`}</small></div></div>}
    {(points.loading || queue.loading || dashboard.loading || alerts.loading) && <Loading label="Atualizando monitor…" />}{error && <ErrorState error={error} onRetry={points.reload} />}
    <div className={styles.columns}><Card><div className={styles.sectionTitle}><h2>Fila operacional</h2><span>{queue.data?.length ?? 0} pontos</span></div>{queue.data?.length === 0 && <EmptyState title="Fila vazia" description="Nenhum ponto aguarda transmissão." />}{queue.data && queue.data.length > 0 && <div className={styles.tableWrap}><table><thead><tr><th>Prioridade</th><th>Ponto</th><th>Zona</th><th>Entrada</th><th>Tentativas</th><th>Status</th></tr></thead><tbody>{queue.data.map((point) => <tr key={point.id}><td>P{point.priority}</td><td><Link to={`/transmission/${point.id}`}>{point.identification}</Link><small>{point.pollingPlace.name}</small></td><td>{point.electoralZone.number}</td><td>{point.queuedAt ? new Date(point.queuedAt).toLocaleString("pt-BR") : "—"}</td><td>{point.attemptCount}<small>{point.lastError || ""}</small></td><td><Badge tone={tone(point.status)}>{TRANSMISSION_LABELS[point.status]}</Badge></td></tr>)}</tbody></table></div>}</Card>
      <Card><div className={styles.sectionTitle}><h2>Alertas ativos</h2><span>{alerts.data?.length ?? 0}</span></div><div className={styles.alerts}>{alerts.data?.map((alert) => <article key={alert.id}><Badge tone="danger">{alert.type.replaceAll("_", " ")}</Badge><strong>{alert.point?.identification}</strong><p>{alert.message}</p><small>{new Date(alert.createdAt).toLocaleString("pt-BR")}</small>{alert.status === "OPEN" && <Button onClick={() => void acknowledge(alert.id)}>Reconhecer</Button>}</article>)}</div></Card></div>
    <Card><h2>Pontos de transmissão</h2>{points.data?.length === 0 ? <EmptyState title="Nenhum ponto" description="Cadastre o primeiro ponto de transmissão." action={<LinkButton to="/transmission/new">Cadastrar ponto</LinkButton>} /> : <div className={styles.pointGrid}>{points.data?.map((point) => <Link key={point.id} to={`/transmission/${point.id}`}><strong>{point.identification}</strong><span>{point.pollingPlace.name} · Zona {point.electoralZone.number}</span><div><Badge tone={tone(point.status)}>{TRANSMISSION_LABELS[point.status]}</Badge><Badge tone={point.connectivity === "ONLINE" ? "success" : point.connectivity === "OFFLINE" ? "danger" : "warning"}>{CONNECTIVITY_LABELS[point.connectivity]}</Badge></div></Link>)}</div>}</Card>
  </section>;
}
