import { Button, ErrorState, LinkButton, Loading, useAsync } from "@eops/ui";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { HandoverNav } from "../components/HandoverNav";
import { shiftHandoversService, statusLabel } from "../services/shiftHandoversService";
import styles from "../styles/shift-handovers.module.css";

export function HandoverDetailPage() {
  const { id = "" } = useParams(); const state = useAsync(() => shiftHandoversService.detail(id), [id]); const [busy, setBusy] = useState(false); const [actionError, setActionError] = useState<Error>();
  async function act(action: 'submit' | 'confirm' | 'cancel') { setBusy(true); setActionError(undefined); try { if (action === 'cancel') { const reason = state.data?.status === 'PENDING_CONFIRMATION' ? window.prompt('Motivo do cancelamento:') ?? undefined : undefined; if (state.data?.status === 'PENDING_CONFIRMATION' && !reason) return; await shiftHandoversService.cancel(id, reason); } else await shiftHandoversService[action](id); state.reload(); } catch (reason) { setActionError(reason instanceof Error ? reason : new Error('Ação não concluída.')); } finally { setBusy(false); } }
  if (state.loading) return <Loading />; if (state.error || !state.data) return <ErrorState error={state.error ?? new Error('Passagem não encontrada.')} onRetry={state.reload} />; const item = state.data;
  return <section className={styles.page}><HandoverNav /><header className={styles.header}><div><span>Operações · Passagem</span><h1>{item.shift.name ?? 'Turno'}</h1><p>{statusLabel[item.status]} · {item.sender.name} → {item.recipient.name}</p></div><div className={styles.actions}>{item.availableActions.includes('edit') && <LinkButton to={`/shift-handovers/${id}/edit`} secondary>Editar</LinkButton>}{item.availableActions.includes('submit') && <Button disabled={busy} onClick={() => act('submit')}>Enviar</Button>}{item.availableActions.includes('confirm') && <Button disabled={busy} onClick={() => act('confirm')}>Confirmar recebimento</Button>}{item.availableActions.includes('cancel') && <Button secondary disabled={busy} onClick={() => act('cancel')}>Cancelar</Button>}</div></header>{actionError && <ErrorState error={actionError} />}
    <div className={styles.detailGrid}><main className={styles.stack}><section className={styles.panel}><h2>Resumo</h2><p>{item.summary || 'Resumo ainda não informado.'}</p>{item.pendingNotes && <><h3>Pendências</h3><p>{item.pendingNotes}</p></>}{item.observations && <><h3>Observações</h3><p>{item.observations}</p></>}<div className={styles.meta}><div><span>Status</span><strong>{statusLabel[item.status]}</strong></div><div><span>Turno</span><Link to={`/shifts/${item.shiftId}`}>{item.shift.name ?? 'Abrir turno'}</Link></div><div><span>Início</span><strong>{new Date(item.shift.startsAt).toLocaleString('pt-BR')}</strong></div><div><span>Local</span><strong>{item.shift.pollingPlace?.name ?? item.shift.electoralZone?.name ?? 'Não informado'}</strong></div><div><span>Enviada</span><strong>{item.submittedAt ? new Date(item.submittedAt).toLocaleString('pt-BR') : 'Ainda não'}</strong></div><div><span>Confirmada</span><strong>{item.confirmedAt ? new Date(item.confirmedAt).toLocaleString('pt-BR') : 'Ainda não'}</strong></div></div></section>
      <ReferenceLinks item={item} />
    </main><aside className={styles.stack}><section className={styles.panel}><h2>Participantes</h2><p><strong>Remetente</strong><br />{item.sender.name}<br /><small>{item.sender.email}</small></p><p><strong>Destinatário</strong><br />{item.recipient.name}<br /><small>{item.recipient.email}</small></p></section><section className={styles.panel}><h2>Histórico</h2><ul className={styles.history}>{item.history.map((entry) => <li key={entry.id}><strong>{entry.action}</strong>{entry.description}<br /><small>{entry.actor?.name ?? 'Sistema'} · {new Date(entry.createdAt).toLocaleString('pt-BR')}</small></li>)}</ul></section></aside></div>
  </section>;
}

function ReferenceLinks({ item }: { item: Awaited<ReturnType<typeof shiftHandoversService.detail>> }) { return <section className={styles.panel}><h2>Contexto associado</h2><div className={styles.links}>{item.incidents.map(({ incident }) => <Link key={incident.id} to={`/incidents/${incident.id}`}>{incident.code} · {incident.title}</Link>)}{item.tasks.map(({ task }) => <Link key={task.id} to={`/tasks/${task.id}`}>{task.title}</Link>)}{item.assets.map(({ asset }) => <Link key={asset.id} to={`/inventory/${asset.id}`}>{asset.assetTag} · {asset.name}</Link>)}{!item.incidents.length && !item.tasks.length && !item.assets.length && <p>Nenhuma referência associada.</p>}</div></section>; }
