import { useEffect, useState, type FormEvent } from "react";
import { Button, Card, EmptyState, ErrorState, Field, Input, Loading, Select, useAsync } from "@eops/ui";
import type { ElectionSummary, FailureProbability } from "@eops/shared";
import { Link, useNavigate } from "react-router-dom";
import { simulatorService } from "../services/simulatorService";
import styles from "../styles/simulator.module.css";

export function SimulatorPage() {
  const navigate = useNavigate(); const simulations = useAsync(simulatorService.list, []); const [elections, setElections] = useState<ElectionSummary[]>([]);
  const [name, setName] = useState("Simulação do dia da eleição"); const [electionId, setElection] = useState(""); const [speed, setSpeed] = useState(5); const [probability, setProbability] = useState<FailureProbability>("MEDIUM"); const [flags, setFlags] = useState({ connectivity: true, equipment: true, transmission: true, logistics: true }); const [apply, setApply] = useState(false); const [error, setError] = useState<unknown>();
  useEffect(() => { void simulatorService.elections().then((items) => { setElections(items); setElection((current) => current || items[0]?.id || ""); }); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(undefined); try { const simulation = await simulatorService.create({ name, electionId, speed, probability, ...flags, applyToOperations: apply }); navigate(`/simulator/${simulation.id}`); } catch (cause) { setError(cause); } }
  return <section className={styles.page}><header><span>SIMULAÇÃO</span><h1>Simulador Operacional</h1><p>Treine respostas e acompanhe incidentes simulados sem confundi-los com ocorrências reais.</p></header>{error !== undefined && <ErrorState error={error} />}<div className={styles.grid}><Card><h2>Nova simulação</h2><form onSubmit={(event) => void submit(event)}><Field label="Nome"><Input required value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Pleito"><Select required value={electionId} onChange={(event) => setElection(event.target.value)}>{elections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Velocidade"><Select value={speed} onChange={(event) => setSpeed(Number(event.target.value))}>{[1, 5, 20, 100].map((value) => <option key={value} value={value}>{value}x</option>)}</Select></Field><Field label="Probabilidade"><Select value={probability} onChange={(event) => setProbability(event.target.value as FailureProbability)}><option value="LOW">Baixa</option><option value="MEDIUM">Média</option><option value="HIGH">Alta</option></Select></Field><fieldset><legend>Falhas automáticas</legend>{Object.entries(flags).map(([key, checked]) => <label key={key}><input type="checkbox" checked={checked} onChange={(event) => setFlags((current) => ({ ...current, [key]: event.target.checked }))} /> {key}</label>)}</fieldset><label className={styles.warning}><input type="checkbox" checked={apply} onChange={(event) => setApply(event.target.checked)} /> Aplicar temporariamente o estado aos ativos (restaurado ao encerrar)</label><Button type="submit">Criar simulação</Button></form></Card><Card><h2>Execuções</h2>{simulations.loading && <Loading />}{simulations.error && <ErrorState error={simulations.error} onRetry={simulations.reload} />}{simulations.data?.length === 0 && <EmptyState title="Nenhuma simulação" description="Configure a primeira execução." />}<ul className={styles.runs}>{simulations.data?.map((item) => <li key={item.id}><div><Link to={`/simulator/${item.id}`}>{item.name}</Link><span>{item.election.name} · {item.speed}x · {item.probability}</span></div><b data-status={item.status}>{item.status}</b><small>{item._count?.events ?? 0} eventos</small></li>)}</ul></Card></div></section>;
}
