import { useState, type FormEvent } from "react";
import { Badge, Button, Card, EmptyState, ErrorState, Field, Input, Loading, Select, useAsync } from "@eops/ui";
import { useSearchParams } from "react-router-dom";
import { routesService } from "../../services/routesService";
import { DELIVERY_STATUS_LABELS } from "../../types";
import styles from "../../styles/overview.module.css";

export function DeliveriesPage() {
  const [params, setParams] = useSearchParams();
  const selectedId = params.get("routeId") ?? "";
  const routes = useAsync(routesService.list, []);
  const references = useAsync(routesService.references, []);
  const selected = useAsync(() => selectedId ? routesService.get(selectedId) : Promise.resolve(undefined), [selectedId]);
  const [batch, setBatch] = useState({ code: "", description: "" });
  const [delivery, setDelivery] = useState({ pollingPlaceId: "", batchId: "", receiverName: "", description: "", quantity: "1", lotCode: "" });
  const [error, setError] = useState<Error>();
  const places = references.data?.places.filter((place) => place.electoralZoneId === selected.data?.electoralZoneId) ?? [];
  async function createBatch(event: FormEvent) { event.preventDefault(); if (!selectedId) return; try { await routesService.createBatch({ routeId: selectedId, ...batch }); setBatch({ code: "", description: "" }); selected.reload(); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Falha ao criar lote.")); } }
  async function createDelivery(event: FormEvent) { event.preventDefault(); if (!selectedId) return; try { await routesService.createDelivery({ routeId: selectedId, pollingPlaceId: delivery.pollingPlaceId, batchId: delivery.batchId || undefined, receiverName: delivery.receiverName || undefined, items: [{ description: delivery.description, quantity: Number(delivery.quantity), lotCode: delivery.lotCode || undefined }] }); setDelivery({ pollingPlaceId: "", batchId: "", receiverName: "", description: "", quantity: "1", lotCode: "" }); selected.reload(); } catch (reason) { setError(reason instanceof Error ? reason : new Error("Falha ao criar entrega.")); } }
  async function update(id: string, status: "IN_TRANSIT" | "DELIVERED" | "FAILED" | "RETURNED") { const failureReason = status === "FAILED" ? window.prompt("Justificativa da falha:") ?? "" : undefined; if (status === "FAILED" && !failureReason) return; await routesService.updateDelivery(id, { status, failureReason }); selected.reload(); }
  return <section className={styles.page}><header className={styles.header}><div><span className={styles.tag}>DISTRIBUIÇÃO</span><h1>Entregas e lotes</h1><p>Acompanhe itens, recebimento, comprovantes e falhas.</p></div></header>
    <Field label="Rota"><Select value={selectedId} onChange={(event) => setParams(event.target.value ? { routeId: event.target.value } : {})}><option value="">Selecione uma rota</option>{routes.data?.map((route) => <option key={route.id} value={route.id}>{route.code} · {route.name}</option>)}</Select></Field>
    {(routes.loading || selected.loading || references.loading) && <Loading label="Carregando entregas…" />}{(error || selected.error) && <ErrorState error={error ?? selected.error} />}
    {!selectedId && !routes.loading && <EmptyState title="Selecione uma rota" description="As entregas e os lotes serão exibidos para a rota selecionada." />}
    {selected.data && <><div className={styles.detailGrid}><Card><h2>Novo lote</h2><form className={styles.compactForm} onSubmit={createBatch}><Field label="Código"><Input required value={batch.code} onChange={(event) => setBatch((value) => ({ ...value, code: event.target.value }))} /></Field><Field label="Descrição"><Input value={batch.description} onChange={(event) => setBatch((value) => ({ ...value, description: event.target.value }))} /></Field><Button type="submit">Criar lote</Button></form></Card><Card><h2>Nova entrega</h2><form className={styles.compactForm} onSubmit={createDelivery}><Field label="Local"><Select required value={delivery.pollingPlaceId} onChange={(event) => setDelivery((value) => ({ ...value, pollingPlaceId: event.target.value }))}><option value="">Selecione</option>{places.map((place) => <option key={place.id} value={place.id}>{place.name}</option>)}</Select></Field><Field label="Lote"><Select value={delivery.batchId} onChange={(event) => setDelivery((value) => ({ ...value, batchId: event.target.value }))}><option value="">Sem lote</option>{selected.data?.batches.map((item) => <option key={item.id} value={item.id}>{item.code}</option>)}</Select></Field><Field label="Item/equipamento"><Input required value={delivery.description} onChange={(event) => setDelivery((value) => ({ ...value, description: event.target.value }))} /></Field><Field label="Quantidade"><Input required min="1" type="number" value={delivery.quantity} onChange={(event) => setDelivery((value) => ({ ...value, quantity: event.target.value }))} /></Field><Field label="Código do lote do item"><Input value={delivery.lotCode} onChange={(event) => setDelivery((value) => ({ ...value, lotCode: event.target.value }))} /></Field><Field label="Responsável pelo recebimento"><Input value={delivery.receiverName} onChange={(event) => setDelivery((value) => ({ ...value, receiverName: event.target.value }))} /></Field><Button type="submit">Criar entrega</Button></form></Card></div>
      {selected.data.deliveries.length === 0 ? <EmptyState title="Sem entregas" description="Cadastre a primeira entrega para esta rota." /> : <div className={styles.tableWrap}><table><thead><tr><th>Local</th><th>Itens</th><th>Status</th><th>Recebimento</th><th>Ações</th></tr></thead><tbody>{selected.data.deliveries.map((item) => <tr key={item.id}><td>{item.pollingPlace.name}</td><td>{item.items.map((entry) => `${entry.quantity}× ${entry.description}`).join(", ")}</td><td><Badge tone={item.status === "DELIVERED" ? "success" : item.status === "FAILED" ? "danger" : "neutral"}>{DELIVERY_STATUS_LABELS[item.status]}</Badge></td><td>{item.receiverName || "—"}<small>{item.deliveredAt ? new Date(item.deliveredAt).toLocaleString("pt-BR") : ""}</small></td><td><div className={styles.rowActions}>{item.status === "PENDING" && <Button onClick={() => void update(item.id, "IN_TRANSIT")}>Em trânsito</Button>}{["PENDING", "IN_TRANSIT"].includes(item.status) && <Button onClick={() => void update(item.id, "DELIVERED")}>Entregar</Button>}{["PENDING", "IN_TRANSIT"].includes(item.status) && <Button onClick={() => void update(item.id, "FAILED")}>Falha</Button>}{item.status === "DELIVERED" && <Button onClick={() => void update(item.id, "RETURNED")}>Recolher</Button>}</div></td></tr>)}</tbody></table></div>}
    </>}
  </section>;
}
