import { useEffect, useState, type FormEvent } from "react";
import { Button, ErrorState, Field, Input, Loading, Select, useAsync } from "@eops/ui";
import { useNavigate, useParams } from "react-router-dom";
import { routesService } from "../../services/routesService";
import type { RouteInput } from "../../types";
import styles from "../../styles/overview.module.css";

type FormState = Omit<RouteInput, "originLatitude" | "originLongitude" | "destinationLatitude" | "destinationLongitude" | "stops"> & { originLatitude: string; originLongitude: string; destinationLatitude: string; destinationLongitude: string; stops: Array<{ pollingPlaceId: string; description: string; eta: string }> };
const empty: FormState = { code: "", name: "", electionId: "", electoralZoneId: "", description: "", originName: "", originLatitude: "", originLongitude: "", destinationName: "", destinationLatitude: "", destinationLongitude: "", plannedDeparture: "", plannedArrival: "", responsibleName: "", driverName: "", vehicleId: "", notes: "", status: "PLANNED", stops: [] };
const localValue = (value: string) => new Date(value).toISOString().slice(0, 16);

export function RouteFormPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [form, setForm] = useState<FormState>(empty);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<Error>();
  const references = useAsync(routesService.references, []);
  const vehicles = useAsync(routesService.vehicles, []);
  const current = useAsync(() => id ? routesService.get(id) : Promise.resolve(undefined), [id]);
  useEffect(() => { if (current.data) setForm({ code: current.data.code, name: current.data.name, electionId: current.data.electionId, electoralZoneId: current.data.electoralZoneId, description: current.data.description ?? "", originName: current.data.originName, originLatitude: String(current.data.originLatitude ?? ""), originLongitude: String(current.data.originLongitude ?? ""), destinationName: current.data.destinationName, destinationLatitude: String(current.data.destinationLatitude ?? ""), destinationLongitude: String(current.data.destinationLongitude ?? ""), plannedDeparture: localValue(current.data.plannedDeparture), plannedArrival: localValue(current.data.plannedArrival), responsibleName: current.data.responsibleName, driverName: current.data.driverName ?? "", vehicleId: current.data.vehicleId ?? "", notes: current.data.notes ?? "", status: current.data.status, stops: current.data.stops.map((stop) => ({ pollingPlaceId: stop.pollingPlaceId ?? "", description: stop.description, eta: localValue(stop.eta) })) }); }, [current.data]);
  const set = (key: keyof FormState, value: string) => setForm((state) => ({ ...state, [key]: value }));
  const zones = references.data?.zones.filter((zone) => !form.electionId || zone.electionId === form.electionId) ?? [];
  const places = references.data?.places.filter((place) => !form.electoralZoneId || place.electoralZoneId === form.electoralZoneId) ?? [];
  const addStop = () => setForm((state) => ({ ...state, stops: [...state.stops, { pollingPlaceId: "", description: "", eta: state.plannedArrival }] }));
  const updateStop = (index: number, key: "pollingPlaceId" | "description" | "eta", value: string) => setForm((state) => ({ ...state, stops: state.stops.map((stop, position) => position === index ? { ...stop, [key]: value } : stop) }));
  const removeStop = (index: number) => setForm((state) => ({ ...state, stops: state.stops.filter((_, position) => position !== index) }));
  async function submit(event: FormEvent) {
    event.preventDefault(); setSaving(true); setError(undefined);
    const numeric = (value: string) => value === "" ? undefined : Number(value);
    const input: RouteInput = { ...form, originLatitude: numeric(form.originLatitude), originLongitude: numeric(form.originLongitude), destinationLatitude: numeric(form.destinationLatitude), destinationLongitude: numeric(form.destinationLongitude), plannedDeparture: new Date(form.plannedDeparture).toISOString(), plannedArrival: new Date(form.plannedArrival).toISOString(), vehicleId: form.vehicleId || undefined, stops: form.stops.map((stop, index) => ({ ...stop, order: index + 1, pollingPlaceId: stop.pollingPlaceId || undefined, eta: new Date(stop.eta).toISOString() })) };
    try { const route = id ? await routesService.update(id, input) : await routesService.create(input); navigate(`/routes/${route.id}`); }
    catch (reason) { setError(reason instanceof Error ? reason : new Error("Não foi possível salvar a rota.")); }
    finally { setSaving(false); }
  }
  if ((id && current.loading) || references.loading || vehicles.loading) return <Loading label="Carregando formulário…" />;
  return <section className={styles.page}><header className={styles.header}><div><span className={styles.tag}>ROTAS</span><h1>{id ? "Editar rota" : "Nova rota"}</h1><p>Defina operação, veículo, horários e sequência de paradas.</p></div></header>{(error || current.error) && <ErrorState error={error ?? current.error} />}
    <form className={styles.form} onSubmit={submit}>
      <div className={styles.formGrid}><Field label="Código"><Input required disabled={Boolean(id)} value={form.code} onChange={(event) => set("code", event.target.value)} /></Field><Field label="Nome"><Input required value={form.name} onChange={(event) => set("name", event.target.value)} /></Field><Field label="Pleito"><Select required disabled={Boolean(id)} value={form.electionId} onChange={(event) => set("electionId", event.target.value)}><option value="">Selecione</option>{references.data?.elections.map((election) => <option key={election.id} value={election.id}>{election.name}</option>)}</Select></Field><Field label="Zona eleitoral"><Select required disabled={Boolean(id)} value={form.electoralZoneId} onChange={(event) => set("electoralZoneId", event.target.value)}><option value="">Selecione</option>{zones.map((zone) => <option key={zone.id} value={zone.id}>Zona {zone.number} · {zone.name}</option>)}</Select></Field><Field label="Responsável"><Input required value={form.responsibleName} onChange={(event) => set("responsibleName", event.target.value)} /></Field><Field label="Motorista"><Input value={form.driverName} onChange={(event) => set("driverName", event.target.value)} /></Field><Field label="Veículo"><Select value={form.vehicleId} onChange={(event) => set("vehicleId", event.target.value)}><option value="">Sem veículo</option>{vehicles.data?.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.identification} · {vehicle.plate}</option>)}</Select></Field><Field label="Status"><Select value={form.status} onChange={(event) => set("status", event.target.value)}><option value="PLANNED">Planejada</option><option value="READY">Pronta</option><option value="IN_PROGRESS">Em andamento</option><option value="DELAYED">Atrasada</option><option value="COMPLETED">Concluída</option><option value="CANCELLED">Cancelada</option></Select></Field></div>
      <div className={styles.formGrid}><Field label="Origem"><Input required value={form.originName} onChange={(event) => set("originName", event.target.value)} /></Field><Field label="Latitude origem"><Input type="number" step="any" value={form.originLatitude} onChange={(event) => set("originLatitude", event.target.value)} /></Field><Field label="Longitude origem"><Input type="number" step="any" value={form.originLongitude} onChange={(event) => set("originLongitude", event.target.value)} /></Field><Field label="Destino"><Input required value={form.destinationName} onChange={(event) => set("destinationName", event.target.value)} /></Field><Field label="Latitude destino"><Input type="number" step="any" value={form.destinationLatitude} onChange={(event) => set("destinationLatitude", event.target.value)} /></Field><Field label="Longitude destino"><Input type="number" step="any" value={form.destinationLongitude} onChange={(event) => set("destinationLongitude", event.target.value)} /></Field><Field label="Saída planejada"><Input required type="datetime-local" value={form.plannedDeparture} onChange={(event) => set("plannedDeparture", event.target.value)} /></Field><Field label="Chegada planejada"><Input required type="datetime-local" value={form.plannedArrival} onChange={(event) => set("plannedArrival", event.target.value)} /></Field></div>
      <Field label="Descrição"><textarea className={styles.textarea} value={form.description} onChange={(event) => set("description", event.target.value)} /></Field><Field label="Observações"><textarea className={styles.textarea} value={form.notes} onChange={(event) => set("notes", event.target.value)} /></Field>
      {!id && <div className={styles.stopsEditor}><div className={styles.sectionTitle}><h2>Paradas</h2><Button type="button" onClick={addStop}>Adicionar parada</Button></div>{form.stops.map((stop, index) => <div className={styles.stopEditor} key={index}><strong>{index + 1}</strong><Select value={stop.pollingPlaceId} onChange={(event) => updateStop(index, "pollingPlaceId", event.target.value)}><option value="">Local opcional</option>{places.map((place) => <option key={place.id} value={place.id}>{place.name}</option>)}</Select><Input required placeholder="Descrição" value={stop.description} onChange={(event) => updateStop(index, "description", event.target.value)} /><Input required type="datetime-local" value={stop.eta} onChange={(event) => updateStop(index, "eta", event.target.value)} /><Button type="button" onClick={() => removeStop(index)}>Remover</Button></div>)}</div>}
      <div className={styles.actions}><Button disabled={saving} type="submit">{saving ? "Salvando…" : "Salvar rota"}</Button></div>
    </form>
  </section>;
}
