import { useState } from "react";
import { Button, Card, ErrorState, Loading, Select, Input, useAsync } from "@eops/ui";
import { BarChart } from "../components/BarChart";
import { reportsService } from "../../services/reportsService";
import type { ReportFilters } from "../../types";
import styles from "../../styles/overview.module.css";

const statusOptions = ["NEW", "TRIAGED", "ASSIGNED", "IN_PROGRESS", "RESOLVED", "CLOSED", "CANCELLED", "AVAILABLE", "ALLOCATED", "IN_TRANSIT", "IN_USE", "MAINTENANCE", "LOST", "RETIRED", "PLANNED", "READY", "DELAYED", "COMPLETED", "WAITING", "QUEUED", "TRANSMITTING", "SUCCESS", "FAILED", "RETRYING", "OFFLINE"];

export function ReportsDashboardPage() {
  const [filters, setFilters] = useState<ReportFilters>({});
  const report = useAsync(() => reportsService.executive(filters), [JSON.stringify(filters)]);
  const references = useAsync(reportsService.references, []);
  const [exporting, setExporting] = useState(false);
  const change = (key: keyof ReportFilters, value: string) => setFilters((current) => ({ ...current, [key]: value || undefined }));
  const zones = references.data?.zones.filter((zone) => !filters.electionId || zone.electionId === filters.electionId) ?? [];
  const places = references.data?.places.filter((place) => !filters.zoneId || place.electoralZoneId === filters.zoneId) ?? [];
  async function runExport(kind: "csv" | "pdf") { setExporting(true); try { await (kind === "csv" ? reportsService.exportCsv(filters) : reportsService.exportPdf(filters)); } finally { setExporting(false); } }
  return <section className={styles.page}><header className={styles.header}><div><span className={styles.tag}>ANALYTICS</span><h1>Relatórios e BI</h1><p>Indicadores calculados sobre dados persistidos de eleições, operação, incidentes, inventário, logística e transmissão.</p></div><div className={styles.actions}><Button disabled={exporting} onClick={() => void runExport("csv")}>Exportar CSV</Button><Button disabled={exporting} onClick={() => void runExport("pdf")}>Exportar PDF</Button></div></header>
    <div className={styles.filters}><Input aria-label="Data inicial" type="date" value={filters.from ?? ""} onChange={(event) => change("from", event.target.value)} /><Input aria-label="Data final" type="date" value={filters.to ?? ""} onChange={(event) => change("to", event.target.value)} /><Select aria-label="Pleito" value={filters.electionId ?? ""} onChange={(event) => change("electionId", event.target.value)}><option value="">Todos os pleitos</option>{references.data?.elections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="Zona" value={filters.zoneId ?? ""} onChange={(event) => change("zoneId", event.target.value)}><option value="">Todas as zonas</option>{zones.map((item) => <option key={item.id} value={item.id}>Zona {item.number} · {item.name}</option>)}</Select><Select aria-label="Local" value={filters.pollingPlaceId ?? ""} onChange={(event) => change("pollingPlaceId", event.target.value)}><option value="">Todos os locais</option>{places.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="Categoria" value={filters.categoryId ?? ""} onChange={(event) => change("categoryId", event.target.value)}><option value="">Todas as categorias</option>{references.data?.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="Status" value={filters.status ?? ""} onChange={(event) => change("status", event.target.value)}><option value="">Todos os status</option>{[...new Set(statusOptions)].sort().map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</Select><Button onClick={() => setFilters({})}>Limpar filtros</Button></div>
    {report.loading && <Loading label="Consolidando indicadores…" />}{report.error && <ErrorState error={report.error} onRetry={report.reload} />}{report.data && <><div className={styles.metrics}>{Object.entries({ "Locais operacionais": report.data.executive.operationalPlaces, "Locais críticos": report.data.executive.criticalPlaces, "Incidentes abertos": report.data.executive.openIncidents, "SLA": `${report.data.executive.slaPercentage}%`, "Ativos disponíveis": report.data.executive.availableAssets, "Ativos indisponíveis": report.data.executive.unavailableAssets, "Transmissão": `${report.data.executive.transmissionPercentage}%`, "Rotas em execução": report.data.executive.routesInProgress, "Entregas atrasadas": report.data.executive.delayedDeliveries, "Equipes ativas": report.data.executive.teamsAvailable ? report.data.executive.activeTeams : "Aguardando módulo" }).map(([label, value]) => <Card key={label}><span>{label}</span><strong>{value}</strong></Card>)}</div>
      <div className={styles.grid}><Card><h2>Incidentes</h2><div className={styles.chartGrid}><BarChart title="Por severidade" data={report.data.incidents.bySeverity} /><BarChart title="Por categoria" data={report.data.incidents.byCategory} /><BarChart title="Por status" data={report.data.incidents.byStatus} /><BarChart title="Evolução diária" data={report.data.incidents.timeline} /></div><div className={styles.inlineMetrics}><span>Tempo médio de resolução <strong>{report.data.incidents.averageResolutionMinutes} min</strong></span><span>SLA <strong>{report.data.incidents.slaPercentage}%</strong></span></div></Card>
      <Card><h2>Inventário e disponibilidade</h2><div className={styles.chartGrid}><BarChart title="Ativos por status" data={report.data.inventory.byStatus} /><BarChart title="Por condição" data={report.data.inventory.byCondition} /><BarChart title="Por tipo" data={report.data.inventory.byType} /></div><div className={styles.inlineMetrics}><span>Movimentações <strong>{report.data.inventory.movements}</strong></span><span>Disponibilidade de ativos <strong>{report.data.availability.availableAssetsPercentage}%</strong></span><span>Locais operacionais <strong>{report.data.availability.operationalPlacesPercentage}%</strong></span></div></Card>
      <Card><h2>Transmissão e logística</h2><div className={styles.chartGrid}><BarChart title="Transmissão por status" data={report.data.transmission.byStatus} /><BarChart title="Conectividade" data={report.data.transmission.byConnectivity} /></div><div className={styles.inlineMetrics}><span>Pontos online <strong>{report.data.availability.onlineTransmissionPoints}</strong></span><span>Rotas atrasadas <strong>{report.data.logistics.delayedRoutes}</strong></span></div></Card></div>
      <Card><h2>Indicadores por zona</h2><div className={styles.tableWrap}><table><thead><tr><th>Zona</th><th>Locais</th><th>Críticos</th><th>Incidentes</th><th>Ativos</th><th>Rotas ativas</th><th>Transmissão</th><th>Equipes</th></tr></thead><tbody>{report.data.byZone.map((zone) => <tr key={zone.id}><td>{zone.label}</td><td>{zone.places}</td><td>{zone.criticalPlaces}</td><td>{zone.openIncidents}</td><td>{zone.assets}</td><td>{zone.routesInProgress}</td><td>{zone.transmissionPercentage}%</td><td>{report.data?.executive.teamsAvailable ? zone.activeTeams : "—"}</td></tr>)}</tbody></table></div></Card>
      <Card><h2>Indicadores por local</h2><div className={styles.tableWrap}><table><thead><tr><th>Local</th><th>Monitoramento</th><th>Incidentes</th><th>Ativos</th><th>Transmissão</th></tr></thead><tbody>{report.data.byPlace.map((place) => <tr key={place.id}><td>{place.label}</td><td>{place.monitoringStatus}</td><td>{place.openIncidents}</td><td>{place.assets}</td><td>{place.transmissionStatus ?? "—"}</td></tr>)}</tbody></table></div></Card>
      <Card><h2>Comparação histórica</h2>{report.data.history.available && report.data.history.previous ? <div className={styles.inlineMetrics}><span>Incidentes no período <strong>{report.data.history.current.incidents}</strong> (anterior: {report.data.history.previous.incidents})</span><span>Transmissões concluídas <strong>{report.data.history.current.transmissions}</strong> (anterior: {report.data.history.previous.transmissions})</span></div> : <p>Defina data inicial e final para comparar com o período anterior equivalente.</p>}</Card>
    </>}
  </section>;
}
